export enum InterestNameHelper {
  DATA = 'DATA',
  SOFTWARE = 'SOFTWARE',
  TYPESCRIPT = 'TYPESCRIPT',
  JAVASCRIPT = 'JAVASCRIPT',
  ARCHITECTURE = 'ARCHITECTURE',
  LIBRARIES = 'LIBRARIES',
  SOFTWARE_PATTERNS = 'SOFTWARE PATTERNS',
  DATABASES = 'DATABASES',
  ANGULAR = 'ANGULAR',
  REACT = 'REACT',
  IONIC = 'IONIC',
  FIREBASE = 'FIREBASE',
}
